[project]
name = "videofillergrid"
description = "A single node, VideoFillerGrid Assemble, that joins source clips and (generated) transition clips that bridge them into one video, following an order list, and writes it straight to disk."
version = "1.0.0"
license = "MIT"

classifiers = [
     "Operating System :: OS Independent",
]

[project.urls]
Repository = "https://github.com/bmad4ever/comfyui_videofillergrid"
Documentation = "https://github.com/bmad4ever/comfyui_videofillergrid/blob/main/README.md"
"Bug Tracker" = "https://github.com/bmad4ever/comfyui_videofillergrid/issues"

[tool.comfy]
PublisherId = "bmad4ever"
DisplayName = "comfyui_videofillergrid"
Icon = ""
includes = []
# "requires-comfyui" = ">=0.32.0"  # should work on older versions too, but not tested
